all:chap1 
chap1:1-1 1-2 1-3 1-4
1-1:
gcc -o hello1 chapter1_1.c -lc
1-2:
gcc -o hello2 chapter1_2.c -lc
1-3:
gcc -o hello3 chapter1_3.c -lc
1-4:
gcc -o hello4 chapter1_4.c -lc
chap2:2-1 2-2
2-1:
gcc -o data1 chapter2_1.c -lc
2-2:
gcc -o data2 chapter2_2.c -lc
clean:
rm hello* data* *~
